sudo: true
branches:
  only:
  - master
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
services:
  - postgresql
addons:
  apt:
    packages:
    - unoconv
    - libreoffice
matrix:
  include:
  - os: linux
    python: 3.4
  - os: osx
    language: generic
    env: TERRYFY_PYTHON='system 2'
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/MacPython/terryfy;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment $TERRYFY_PYTHON
  venv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://downloadarchive.documentfoundation.org/libreoffice/old/4.3.7.2/mac/x86_64/LibreOffice_4.2.8.2_MacOS_x86-64.dmg && sudo hdiutil attach LibreOffice_4.2.8.2_MacOS_x86-64.dmg && ln -s /Volumes/LibreOffice/LibreOffice.app/Contents/MacOS/python /tmp/python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install unoconv --HEAD; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
install:
- pip install csvkit
- createdb schools
script:
- make database